101 set up pytest for logging test results
OSSQA-PUM/OSSQA pull request #102
Opened 2024-03-23 13:46 UTC by parslie

This PR configures pytest, all tests, and the docker-image-test workflow so that test results are logged and printed after testing.

2024-03-26 08:10 UTC, grufe approved these changes
Looks good. Seems like a very nice addition to our CI!

2024-03-27 09:13 UTC, edvgi966 requested changes
Minor merge conflict in test_util.py that should be addressed before merge, other than that looks really good!

2024-03-27 13:49 UTC, KarlssonPaGolvet commented
I have no further comments than above. Looks good

2024-03-28 08:51 UTC, edvgi966 approved these changes

2024-03-28 09:04 UTC, merged