Release tags and normal tags including weird names
OSSQA-PUM/OSSQA pull request #197
Opened 2024-05-03 10:38 UTC by KarlssonPaGolvet

Created a new branch because of Git problems, this should work

2024-05-09 11:12 UTC, grufe requested changes
I can accept this PR if the SBOM is removed, but we should look into making the get_git_sha1 function more readable.

2024-05-09 11:12 UTC, grufe commented on src/main/util.py
Very long segment of try-except making this code hard to head. Could this be changed somehow?

2024-05-09 11:12 UTC, grufe commented on src/main/data_types/dependency_scorer.py
Don't think we should want to specify tag type here. This could be handled directly by the get_get_sha1 function.

2024-05-09 11:12 UTC, grufe commented on src/main/util.py
Maybe this should be expanded to a class. Seems like a very long function right now doing multiple things.

2024-05-09 11:12 UTC, grufe commented on sysman-crates.cdx.json
Should not be here!

2024-05-09 16:48 UTC, grufe approved these changes

2024-05-10 12:52 UTC, edvgi966 requested changes

2024-05-10 12:52 UTC, edvgi966 commented on src/main/util.py
> +    try:
Very long nestled try chain

2024-05-10 14:33 UTC, jakob123100 commented
The PR looks overall acceptable to me, however two tests are faling in the latest commit, scored_deps list is empty.
Is there a reason why these tests should fail?

2024-05-10 15:40 UTC, edvgi966 approved these changes

2024-05-10 15:40 UTC, merged