25 create main application structure
OSSQA-PUM/OSSQA pull request #66
Opened 2024-03-04 09:37 UTC by Bacilika

2024-03-04 11:29 UTC, edvgi966 requested changes
MAS.py is missing docstrings

2024-03-04 11:29 UTC, edvgi966 commented on src/MAS.py
Missing Docstrings

2024-03-04 11:34 UTC, jakob123100 requested changes
Add idea files to .gitignore

example add to .gitignore file:
.idea/

2024-03-04 15:00 UTC, edvgi966 approved these changes
Review pass.

2024-03-05 10:49 UTC, jakob123100 approved these changes
Looks good!

2024-03-05 10:52 UTC, merged